apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: grafana
              containerPort: 3000
          resources:
            limits:
              memory: '1Gi'
              cpu: '1000m'
            requests:
              memory: 500M
              cpu: '500m'
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: false
            - name: grafana-dashboard-providers
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: false
            - name: dashboard-1
              mountPath: /var/lib/grafana/dashboards/dashboard-1
            - name: dashboard-2
              mountPath: /var/lib/grafana/dashboards/dashboard-2
          env:
            # - name: GF_SECURITY_ALLOW_EMBEDDING
            #   value: 'true'
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: 'true'
            - name: GF_AUTH_BASIC_ENABLED
              value: 'false'
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: 'Admin'
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-ini
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        - name: grafana-dashboard-providers
          configMap:
            name: grafana-dashboard-providers
        - name: dashboard-1
          configMap:
            name: dashboard-1 
        - name: dashboard-2
          configMap:
            name: dashboard-2 
